force-app/main/default/objects/Product_Line__c.object
<CustomObject>
    <fields>
        <fullName>GBU__c</fullName>
        <label>GBU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Avionics</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Cyber Security</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line_Family__c</fullName>
        <label>Product Line Family</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Line__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Av-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Av-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Av-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL3-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL3-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL3-PL2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Line</label>
    <nameField>
        <label>PL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Produit__c.object
<CustomObject>
    <fields>
        <fullName>GBU__c</fullName>
        <formula>TEXT(Product_Line__r.GBU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GBU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line_Family__c</fullName>
        <label>Product Line Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Av-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Av-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Av-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL3-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL3-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL3-PL2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Produits</relationshipLabel>
        <relationshipName>Produits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Produit</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>GBU__c</fullName>
        <label>GBU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GBU</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/GBU.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avionics</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Cyber Security</fullName>
    </customValue>
    <masterLabel>GBU</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProduitClass.cls
public class ProduitClass {

    public static void InsertDefault(List <Produit__c> os) {
	//    string usergbu = [select GBU__c from User where id = :UserInfo.getUserId()].GBU__c;
	
	//Query lookup Product_Line__c
	Map<Id,Product_Line__c> pMap = new Map<Id,Product_Line__c>();        
    for (Produit__c o:os){
        pMap.put(o.Product_Line__c, null);
    }
	pMap.remove(null);
	pMap.putAll([select Id, Product_Line_Family__c from Product_Line__c where Id in :pMap.keySet()]);        
        
	// update field
    for (Produit__c o:os){    
        o.Product_Line_Family__c = pMap.get(o.Product_Line__c).Product_Line_Family__c;    
    }
    
    // update os;     
}
}