force-app/main/default/objects/Product_Line__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>GBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Avionics - BL 1</fullName>
                </value>
                <value>
                    <fullName>Avionics - BL 2</fullName>
                </value>
                <value>
                    <fullName>Avionics - BL 3</fullName>
                </value>
                <value>
                    <fullName>Electronics - BL 1</fullName>
                </value>
                <value>
                    <fullName>Electronics - BL 2</fullName>
                </value>
                <value>
                    <fullName>Electronics-  BL 3</fullName>
                </value>
                <value>
                    <fullName>Cyb Sec  - BL 1</fullName>
                </value>
                <value>
                    <fullName>Cyb Sec - BL 2</fullName>
                </value>
                <value>
                    <fullName>Cyb Sec - BL 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Free_field_1__c</fullName>
        <label>Free field 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GBU__c</fullName>
        <label>GBU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Avionics</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Cyber Security</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line_Family__c</fullName>
        <label>Product Line Family</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Line__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Av-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Av-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Av-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Av-BL3-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Elec-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Elec-BL3-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL1-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL1-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL2-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL2-PL2</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL3-PL1</fullName>
                </value>
                <value>
                    <fullName>Cyb-BL3-PL2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UniqueKey1__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>BL + PL Name + PL Family</description>
        <label>UniqueKey1</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Line</label>
    <nameField>
        <label>PL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line_Team__c.object
<CustomObject>
    <fields>
        <fullName>Member2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Line_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Product Line Teams</relationshipLabel>
        <relationshipName>Product_Line_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Line Team</label>
    <nameField>
        <label>Member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Line Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>GBU__c</fullName>
        <label>GBU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GBU</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/GBU.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avionics</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Cyber Security</fullName>
    </customValue>
    <masterLabel>GBU</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PLClass.cls
public class PLClass {

public static void CreateDefaultTeam(List <Product_Line__c> PLs) {

    System.Debug('CreateDefaultTeam: start');
    string ownername;
    
    User ownerLKP = new User();
    
    List <Product_Line_Team__c> PLTEAMs = new list <Product_Line_Team__c>();
    map<Id,User> ownerMap = new map<Id,User>();
    
   
    for (Product_Line__c PL:PLs) {
       ownerMap.put(PL.OwnerId, null);
    }
    
    ownerMap.remove(null);
    ownerMap.putAll([Select Id, Name, Alias From User Where Id In : ownerMap.keyset()]);
    
    for (Product_Line__c PL:PLs) {
    
    //    ownername = PL.Name; //OK
          ownername = ownerMap.get(PL.OwnerId).Name; //OK

    
    /*    ownerLKP = [Select Id, Name, Alias From User Where Id = :PL.OwnerId]; //OK: but not to use because of governorlimit: select inside loop
        ownername = ownerLKP.Name;
    */
            
        Product_Line_Team__c PLTEAM = new Product_Line_Team__c(Product_Line__c = PL.id, Name = ownername, Member2__c = PL.CreatedByID, Primary__c = true); 
        PLTEAMs.add(PLTEAM );
    }
    
    insert PLTEAMs;

}


public static void PLInsertDefault(List <Product_Line__c> PLs) {
    
    string usergbu = [select GBU__c from User where id = :UserInfo.getUserId()].GBU__c;
        
    for (Product_Line__c PL:PLs){
        PL.GBU__c = usergbu; // set default user GBU
        PL.Free_field_1__c = 'Update from trigger'; // set sample
        PL.UniqueKey1__c = PL.Business_Line__c + PL.Name + PL.Product_Line_Family__c; // set UnikeyField1
    }    
    
}

}